MetLifeLegalPlans/portunus

- backend/authentication/views.py
Missed this. This fixes the login view.
> Use the right parameter in the login view

- backend/backend/urls.py
- backend/backend/views.py
Adds backend endpoint for #12.
Tested, works as expected.
> Add endpoint to set csrf cookie

- backend/authentication/utils.py
- backend/authentication/views.py
- frontend/components/CompleteResetPassword.js
- frontend/components/ResetPassword.js
- frontend/pages/reset_password.js
- frontend/pages/reset_password/complete/[uuid]/[token].js
- frontend/utils/API.js
Tested through fully, working!
Learned SO MUCH, thanks @swang192 for fielding my many questions >.<
> Add reset password pages

- backend/authentication/serializers.py
- backend/authentication/utils.py
- backend/authentication/views.py
- frontend/components/Login.js
- frontend/components/Register.js
- frontend/utils/API.js
Since we are using some built in Django validators and they provide field-level errors with user-friendly strings I thought I would try leveraging that for our 400 responses. Seems like a simple approach for form-based views. Let me know what you think.
> Handle validation errors on login/reset views

- backend/authentication/utils.py
- backend/authentication/views.py
- backend/backend/settings/__init__.py
- frontend/components/Login.js
- frontend/components/Register.js
Only the last commit is part of this PR. To be merged after #22. Passing the redirect URL through the backend is a little awkward, but I thought it would be good to make sure we don't redirect to arbitrary URLs.
> Redirect on successful authentication

- backend/authentication/utils.py
- backend/authentication/views.py
- frontend/components/CompleteResetPassword.js
- frontend/components/Login.js
- frontend/components/ResetPassword.js
Closes #30 
This adds clear password validation errors on the reset page as well as some other places and fixes some backend issues that came about from a past PR. Tested all of the reset functionality.
> Add in better error messages

- backend/zappa_settings.json
Dev environment created.
Frontend on elastic beanstalk- https://dev.portunus.willing.com/
Backend on lambda- https://api-dev.portunus.willing.com/
> DEPLOYMENT: Add dev env in zappa

- backend/authentication/factories.py
- backend/authentication/serializers.py
- backend/authentication/tests/views/conftest.py
- backend/authentication/tests/views/test_views.py
- backend/authentication/tests/views/utils.py
- backend/authentication/urls.py
- backend/authentication/utils.py
- backend/pytest.ini
- backend/requirements.dev.txt
- codebuild/backend-testing.yml
Little bit of a PR pileup, going to request a review from @markrawls on #34. In the meantime, only the last commit here is part of this PR.
> Add testing

- backend/backend/settings/zygoat_settings.py
Django settings file update from zygoat (https://github.com/MetLifeLegalPlans/zygoat/pull/69)
> SECURITY: Add security HTTP headers

- backend/authentication/serializers.py
- backend/authentication/urls.py
- backend/authentication/views.py
Still thinking about the best way to secure this endpoint, but
adding it like this for now so that members can use it in dev.
Only the last commit is part of this PR. To be merged after #51
> Add user-info view 

- docker-compose.yml
- frontend/Dockerfile
- frontend/Dockerfile.dev
The dev Dockerfile is renamed to `Dockerfile.dev`. 
Non dev builds will be built from `Dockerfile`
> DOCKER: Add configuration to build production image

- backend/backend/urls.py
- backend/backend/views.py
- frontend/pages/index.js
- frontend/store/index.js
It will be useful for other apps to have a path to redirect to rather than an API endpoint to log users out.
> Add logout path

- frontend/utils/API.js
> FRONTEND: use unauthenticatedAPI where appropriate

- backend/backend/settings/zygoat_settings.py
From https://github.com/MetLifeLegalPlans/zygoat/pull/92
Closes https://github.com/MetLifeLegalPlans/portunus/issues/105
> SETTINGS: Set DEBUG flag correctly

- frontend/components/CompleteResetPassword/index.js
Related to one of the changes in https://github.com/MetLifeLegalPlans/portunus/pull/94
Found in UAT
> PASSWORD_RESET: Add password help text

- backend/authentication/utils.py
- frontend/components/ChangePassword.js
- frontend/components/CompleteResetPassword/index.js
> AUTH: redirect to members on successful password reset/change

- backend/authentication/tests/views/test_views.py
- backend/authentication/utils.py
- backend/backend/settings/__init__.py
- backend/backend/views.py
To be used to redirect to legacy members
> BACKEND: allow redirect url to be passed to the logout view

- backend/authentication/templates/email/reset_password.html
> Reset password email template styling

- backend/authentication/factories.py
- backend/authentication/tests/views/test_views.py
- backend/authentication/views.py
- backend/shared/permissions.py
Not sure how I missed this before..
> AUTH: secure user view

- frontend/pages/_document.js
- frontend/public/browserCompatibility.js
Closes https://github.com/MetLifeLegalPlans/members/issues/547
Supersedes https://github.com/MetLifeLegalPlans/portunus/pull/164
Tested locally with IE11 and this is working. Not very happy with the approach though, would appreciate a look from @markrawls and any suggestions on how to do this better.
> Add browser compatibility banner

- frontend/components/BrowserCompatibilityBanner.js
- frontend/pages/_document.js
We could probably use a better long term solution for this, but this updates the banner styles to match what product wants for it.
> FRONTEND: update styles on the browser compatibility banner

- frontend/components/AuthBase.js
This somehow got merged when the tests didn't pass. Making the fix straight to RC.
> Fix lint issue

- frontend/package.json
- frontend/pages/_app.js
- frontend/yarn.lock
Setup for #200.
Same as https://github.com/MetLifeLegalPlans/members/pull/646
> A11Y: add react-axe package

- backend/authentication/tests/views/test_views.py
- backend/backend/settings.py
closes #198 
**Change Password** - ![Change password screen shot](https://user-images.githubusercontent.com/59615718/95918442-cdce8600-0d79-11eb-8d20-6261a0486980.png)
**password 7 chars on register**- ![password lenght 7](https://user-images.githubusercontent.com/59615718/95918445-ce671c80-0d79-11eb-8004-716433f24897.png)
**Password length 8 chars** - ![password length 8](https://user-images.githubusercontent.com/59615718/95918447-ce671c80-0d79-11eb-80ae-52d39c7c0147.png)
**Reset password for existing account with 7 chars-**![reset password](https://user-images.githubusercontent.com/59615718/95918449-ceffb300-0d79-11eb-9dc8-c655b58dd61d.png)
> password length is 8 chars

- backend/authentication/tests/views/test_views.py
- backend/authentication/utils.py
- backend/backend/views.py
Closes PORTUNUS-BACKEND-C, PORTUNUS-BACKEND-E
> BACKEND: avoid errors when unauthenticated user logs out

- backend/authentication/templates/email/reset_password.html
- backend/shared/email.py
> SETTINGS: add support phone number and email address and use in email templates

- backend/authentication/password_validators.py
- backend/backend/settings.py
- backend/requirements.txt
- frontend/components/AuthBase.js
>  BACKEND: Password strength on backend should be restricted to a reasonably good score
